### ISSUE TITLE
#cog dropdown rendered mostly off-window

### ISSUE THREAD

**Issue by arildm** [spraakbanken/korp-frontend#112] opened 2019-10-10 08:13 UTC
On Chrome 77.0.3865.90, but not on Firefox.

<img width="114" alt="Screenshot 2019-10-10 at 10 06 41" src="https://user-images.githubusercontent.com/1454404/66550569-fc51c980-eb45-11e9-98b8-2aaf22986611.png">

If I reduce window width, click the cog, and then restore window width, the dropdown comes into view.

**Comment by majsan** [comment] 2020-03-13 14:37
Duplicate of #20

**Closed by majsan** 2020-03-13 14:37 UTC
